//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraTickets
    {
        public int Id { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public string Categoria { get; set; }
        public string Estado { get; set; }
        public byte[] Evidencia { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> SoportistaAsignadoId { get; set; }
        public Nullable<System.DateTime> FechaFinalizado { get; set; }
    }
}
